modLoader="javafml"
loaderVersion="[4,)"
license="All rights reserved"
issueTrackerURL="https://github.com/pingfanH/OpenYSM/issues"

[[mods]]
modId="yes_steve_model"
version="2.6.5-neoforge+mc1.21.1"
displayName="Yes Steve Model"
displayURL="https://ysm.cfpa.team/"
logoFile="yesstevemodel.png"
credits="bernie-g (GeckoLib), fadookie (mclib), TT432 & SQwatermark (helped me solve many difficult problems)"
authors="YS Group, TartaricAcid, TomatoPuddin, AryochiL"
description="A mod based on GeckoLib that modifies the player model"

[[dependencies.yes_steve_model]]
modId="neoforge"
mandatory=true
versionRange="[21,)"
ordering="NONE"
side="BOTH"

[[dependencies.yes_steve_model]]
modId="minecraft"
mandatory=true
versionRange="[1.21,1.22)"
ordering="NONE"
side="BOTH"

[[dependencies.yes_steve_model]]
modId="tacz"
mandatory=false
versionRange="[1.0.2,)"
ordering="NONE"
side="BOTH"

[[mixins]]
config="yes_steve_model.mixins.json"
